//layout.tsx
import type { Metadata } from 'next'
import RootLayout, { RootLayoutProps } from '../app/page';
import './globals.css'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
    <RootLayout>
      {children}
    </RootLayout>
    </body>
    </html>
  );
};

export default Layout;
